name: Coverage report

on:
  push:
  workflow_dispatch:

jobs:
  coverage-report:
    runs-on: ubuntu-latest
    environment: mastodon
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Checkout original repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            coverage.xml
          sparse-checkout-cone-mode: false
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          flags: unittests
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
