name: Coverage report

on:
  push:
  workflow_dispatch:

jobs:
  coverage-report:
    runs-on: ubuntu-latest
    environment: mastodon
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          flags: unittests
          files: /home/runner/work/FediFetcher/FediFetcher/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
