name: Dependabot Automerge

on:
    push:
        branches:
            - 'main'
    pull_request:
    schedule:
        - cron: '21 23 * * 4'
    workflow_dispatch:

permissions:
    pull-requests: write
    contents: write

jobs:
    dependabot:
        name: 'Dependabot 🤖'
        runs-on: ubuntu-latest
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
        steps:
            - name: Dependabot metadata
              id: dependabot-metadata
              uses: dependabot/fetch-metadata@v1.3.1
              with:
                github-token: "${{ secrets.GITHUB_TOKEN }}"
            - name: Enable auto-merge for Dependabot PRs
              if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
              run: gh pr merge --auto --squash "$PR_URL"
              env:
                PR_URL: ${{github.event.pull_request.html_url}}
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}