name: Dependabot Automerge

on:
  push:
    branches:
      - 'main'
  pull_request:
  schedule:
    - cron: '21 23 * * 4'
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    name: 'Dependabot 🤖'
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]'}}
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.3.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        run: |
          gh pr merge --auto --squash "$PR_URL"
          if [ $? -eq 0 ]; then
            pr_branch="dependabot-$(echo ${{ github.event.pull_request.head.ref }} | sed 's/[^[:alnum:]]/-/g')"
            git checkout -b $pr_branch
            git push origin $pr_branch
            gh workflow run get_context.yml -b $pr_branch
            review_id=$(gh pr view "$PR_URL" --json id --jq '.id')
            gh pr review "$PR_URL" --approve --reviewer @dependabot[bot] --json url --jq '.url'
            gh pr merge "$PR_URL" --squash
          fi
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
